### ISSUE TITLE
Image Manager demo page

### ISSUE THREAD

**Issue by Dante4109** [Dante4109/Vue-Django-Rest-Cookie-Cutter#14]
Objective: Create an image manager page using the old AC image upload component as a base. 

Requirements: 

Setup Amazon S3 blob storage on Django backend
Add image_app to to Django backend

**Comment by Dante4109** [comment]
BUG. 

Image manager scroll where the buttons are obscures bread crumbs. Should be a scroll there at all. 

![Image](https://github.com/user-attachments/assets/8399f48a-bb39-45d9-9925-58257d7a8935)

![Image](https://github.com/user-attachments/assets/8f503c7b-06d1-4732-8321-56ececcca332)

**Comment by Dante4109** [comment]
Warning: 

```
ImageManager.vue:592 [Vue warn]: Invalid prop: type check failed for prop "hideInput". Expected Boolean, got String with value "true". 
  at <VFileInput modelValue=null onUpdate:modelValue=fn onChange=fn  ... > 
  at <VDefaultsProvider key="content-defaults" disabled=true defaults= 
{VIcon: {…}}
 > 
  at <VBtn key=3 > 
  at <VCol class="text-right" cols="12" > 
  at <VRow> 
  at <VCardText> 
  at <VCard> 
  at <VDefaultsProvider root="VDialog" > 
  at <BaseTransition onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave> appear=true  ... > 
  at <Transition name="dialog-transition" appear=true persisted=true  ... > 
  at <VDialogTransition appear=true persisted=true target=undefined  ... > 
  at <MaybeTransition appear=true persisted=true transition= 
{component: {…}}
  ... > 
  at <VOverlay ref=Ref< 
Proxy(Object) {…}
 > class="v-dialog v-dialog--scrollable imageManager" style= 
{}
  ... > 
  at <VDialog class="imageManager" modelValue=true onUpdate:modelValue=fn  ... > 
  at <VLayout row="" justify-center="" > 
  at <VMain> 
  at <ImageManager> 
  at <VCol cols="12" > 
  at <VRow> 
  at <VLayout column="" class="white--text" > 
  at <VContainer> 
  at <Image Manager onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy(Object) {openImageManager: ƒ, …}
 > > 
  at <RouterView key="/demo/imagemanager" > 
  at <VMain> 
  at <VApp> 
  at <App>
```

**Comment by Dante4109** [comment]
Error when attempting to add a new folder. 
```
ImageManager.vue:346 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'push')
    at Proxy.getTreeItemsList (ImageManager.vue:346:37)
    at Proxy.updateImageCollection (ImageManager.vue:542:38)
    at Proxy.addFolderImageManager (ImageManager.vue:457:13)
    at _createVNode.onClick._cache.<computed>._cache.<computed> (ImageManager.vue:38:19)
    at chunk-TF6X5W6F.js?v=1a7f9910:11184:45
    at callWithErrorHandling (chunk-TF6X5W6F.js?v=1a7f9910:2260:19)
    at callWithAsyncErrorHandling (chunk-TF6X5W6F.js?v=1a7f9910:2267:17)
    at callWithAsyncErrorHandling (chunk-TF6X5W6F.js?v=1a7f9910:2278:19)
    at HTMLButtonElement.invoker (chunk-TF6X5W6F.js?v=1a7f9910:11155:5)
```

**Comment by Dante4109** [comment]
Unable to deleted folders with nested objects inside them. 

![Image](https://github.com/user-attachments/assets/7df70cbe-b773-4eea-81cb-405d60f86e16)

**Comment by Dante4109** [comment]
Able to delete nested folders without issue but the following error appears. This does not happen when deleting a folder without any children. 

![Image](https://github.com/user-attachments/assets/4f69d204-4a3b-4ba7-9b4b-1267756664d5)
